apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calculator
  name: calculator
spec:
  # do not include replicas in the manifests if you want replicas to be controlled by HPA
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  strategy: {}
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - image: calculator
          name: calculator
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 50051
              name: grpc
          resources: {}
          env:
            - name: PORT
              value: "3000"
            - name: GRPC_PORT
              value: "50051"
          livenessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:50051
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:50051
            initialDelaySeconds: 10
status: {}
