apiVersion: v1
kind: Service
metadata:
  labels:
    app: calculator
  name: calculator
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
    - port: 50051
      protocol: TCP
      targetPort: 50051
      name: grpc
  selector:
    app: calculator
