apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - name: poc-nextershop-gitops
      url: git@github.com:SCGWEDOtech/trinity-gitops.git
      sshPrivateKeySecret:
        name: repository-secret
        key: trinityGitopsDeployKey
