apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace to deploy all Resources to
namespace: hello-world-dev

# labels added to all Resources
commonLabels:
  region: ap-southeast-1

resources:
- ../base
