apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  # do not include replicas in the manifests if you want replicas to be controlled by HPA
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - image: api-gateway
          name: api-gateway
          ports:
            - containerPort: 3000
              name: http
          resources: {}
          env:
            - name: PORT
              value: "3000"
            - name: GRPC_URL
              value: $(CALCULATOR_SVC).$(CALCULATOR_SVC_NS).svc.cluster.local:50051
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
status: {}
